### ISSUE TITLE
Unable to deploy on railway or replit

### ISSUE THREAD

**Issue by nhineetyy** [Ruby-Network/ruby-v2#16]
Unable to deploy on replit due to it being against community guidelines. No fix for that but railway seems to not deploy.

**Comment by MotorTruck1221** [comment]
It may be due to the size of the build i'll take a look

**Comment by MotorTruck1221** [comment]
Commit 2d0d318ca2251e51eba36a67eea43f04d46b3a98 fixes railway
@monroevilleRAT
